LongName: Scientific Computing and Imaging Institute - VDC test site 1
Description: University of Utah's Scientific Computing and Imaging Institute, 
  located in Salt Lake City. Testing site for the Virtual Data Collaboratory 
  (VDC) initiative.
ID: 
AddressLine1: 155 South 1452 East Room 405
City: Salt Lake City
Country: United States
Latitude: 40.7608
Longitude: -111.891
State: UT
Zipcode: '84112'
